### ISSUE TITLE
Change of PI name on our company SBIR/STTR site

### ISSUE THREAD

**Issue by bchang321** [18F/nsf-sbir#1028]
## Expected Behavior
I'd like to have our PI information updated on your website page for our company. 
Here is the site: 
https://seedfund.nsf.gov/awardees/phase-1/details/?company=kelahealth-inc

PI should be: 
Bora Chang, MD 
919-972-8231
Principal Investigator

## Actual Behavior

Currently it has the old PI: 
Zhifei Sun
281-610-8006
Principal Investigator

## Steps to reproduce the behavior
- [ ] 
- [ ]
- [ ]

## This issue is done when:
- [ ] There is the correct information showing on the site. 
- [ ]
- [ ]

**Comment by kmonterr** [comment]
@seakhtar  - I'm not sure why this is still showing up as the wrong PI - 
Do you mind taking a look? It is correct in the awards database - https://www.nsf.gov/awardsearch/showAward?AWD_ID=1721737&HistoricalAwards=false

**Comment by seakhtar** [comment]
Hi Kelly, 

I will take a look!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So I figured out what was going on. When updating the API, you have to do it manually on each branch- dev, staging, and master- rather than using pull requests. Otherwise, the branch does not properly update the data file and continues to use outdated information.

This goes a against what was in the wiki (which suggests updating locally and then pushing the file to the master branch), so if you have no objections I'm thinking I should change it to reflect this. 

But the companies should now be displaying all updated information!

**Comment by seakhtar** [comment]
Sure- I will discuss it with him and let you know if he has any concerns!
