### ISSUE TITLE
Topics June 2018

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1088]
Hi Sarah!

We have finalized the topics. Do you mind changing the topics on each of the appropriate pages, updating the subtopic lists on the portfolio pages, creating a compliant PDF and replacing the old PDF with the new one? It's a lot! There were a lot of changes, so you might want to just pull the text and replace it with the new text. Let me know if you have any questions or concerns!
THANK YOU!
Best,
Kelly 
[SOLICITATION TOPICS _3.2018-final.docx](https://github.com/18F/nsf-sbir/files/1843424/SOLICITATION.TOPICS._3.2018-final.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Once the fastlane guide is finished up I'll start work on this! 

Just had a quick question about how the directors map out- I'm assuming that for the topics that have been split into two, the director will be the same for them both (ie, DH and MD will both be under Nancy Kamei)? I know the system gets a bit finicky about how PDs and topics interact, so this might be something to note as a possible issue, but I'll let you know how it sorts out once I've made the change in a test branch.

Anyway, I'll keep you informed as I go-

**Comment by kmonterr** [comment]
Thanks, @seakhtar !

Yes....the system is picky! DH and MD are both under Nancy :) Let me know if you have any other issues!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So I decided it might be easier to just make the updates at night so that I don't tie up the system all day tomorrow. 

I've updated the Tech-Topics file with the new topics and subtopics, and created separate topic pages for DH, MD, I and S/PH. I also made the topics document a 508-compliant PDF and uploaded it to replace the previous one:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicUpdateMar18/portfolio/

The one thing I wasn't sure about was how to split the companies (that list on the portfolio page under each topic) between the DH/MD and I/SPH. I just copied the same list over for each pair, but let me know if there's a preferred list for each topic. 

The one major issue that came up is with regards to the Phase I/Phase II pages (that list all the awards). I think splitting what essentially used to be Smart Health into two brand new topics is throwing the system through such a loop that it is now refusing to show any of the awards. 

I will keep trying to figure out what is going on, but even if I do get it to display again, a lot of the awards will still be in the wrong place due to our previous PD-sorting issue. I'm hoping to talk with Dakota's developer next week to see if he has any ideas on how to manage that. 

Anyway, let me know if you find anything off on the topics pages!
-Sarah

**Comment by kmonterr** [comment]
Hi Sarah,

Thank you! I asked the staff if it's OK to put the topics together...I'll let you know what they say!

Did you swap the language for each of the topics on the appropriate pages? The text descriptions changed for most of the topics. The subtopics changed for several of the topics too, so they'll need to be changed on the main portfolio page.

Thanks for working into the night on this! Hopefully, I hear back soon and we can fix this up today!

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Yes- I did notice that most of the subtopic descriptions had changed so I tried to get them all updated with what was on the document. The portfolio descriptions should also reflect the new subtopics as well- they are controlled by the tech-topics file, if you see any that need adjusting.

I'll keep an eye out for the next update!

**Comment by kmonterr** [comment]
Hi Sarah, I think it's OK to combine MD and DH into one page and S/PH and I into another page. Let me know how it goes!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So, I managed to split the topics up again, but the PhaseI/II pages were still not showing their tables. After a bunch of troubleshooting I happened to look at the live site and realized the problem is there as well, meaning the issue must have cropped up sometimes before we started updating the topics. 

I'm still trying to figure out what might have caused it, but in the meantime would you like me to separate those topics again, or just leave them as one?

**Comment by kmonterr** [comment]
Weird!! I wonder what happened??

You can keep them combined. I think that works. Do you want to push the changes live while you and team try to figure out what's happening? That way people can at least see this cycle's topics this weekend!

One other thing I noticed - Other Topics - Do you mind reordering the program directors and put Ben above Anna on the left hand side? He is the primary POC.

Maybe someone from 18F will remember what could be at play with the API and Phase I/II?

**Comment by seakhtar** [comment]
Sure- I'll play with it a little longer, but if I can't figure it out I'll go ahead and push what we have.

**Comment by kmonterr** [comment]
Hi @seakhtar - can you please replace the old topics pdf with the new one on the apply timeline?
There is also a link to the PDF in step one - https://seedfund.nsf.gov/apply/
Download a searchable PDF of the full list of technology topic areas that also includes descriptions of the subtopics.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I saw the link in Step 1, but it sounds like you're saying there are two? Couldn't find a second one- can you point me in the right direction?

**Comment by kmonterr** [comment]
Thanks, Sarah! I think that's the second of two spots? The first one was the link on the portfolio page that you changed last week. Do you know of another location? Maybe you could do a search query to see if it does live somewhere else?

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I did a search and didn't see any more locations, but let me know if you stumble over another one. The old version of the PDF is still cached in the site, so I'll delete it from the system. That way it won't show up in searches. Afterwards, I'll go ahead and push to prod!

**Comment by kmonterr** [comment]
go ahead and push it! thanks, Sarah!

**Comment by seakhtar** [comment]
Okay, this should be all set now!

**Comment by kmonterr** [comment]
Thank you!!
