### ISSUE TITLE
Adding a page - Boot Camp

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1154]
[Boot Camp webpage_final.docx](https://github.com/18F/nsf-sbir/files/2018486/Boot.Camp.webpage_final.docx)

- [ ] I’d like this page to live on the Phase I awardees page: https://seedfund.nsf.gov/resources/awardees/phase-1/
- [ ] On the left navigation as “Boot Camp” make it the second item on the left nav.
- [ ] And, as a bullet under “information for current Phase I awardees.”
- [ ] Please add this file to our site and link to our site instead of DropBox 

 •	Complete the initial draft of your Business Model Canvas  (click to download template)
https://www.dropbox.com/s/rqylkbpddohjumr/the-business-model-canvas.pdf?dl=0

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've got a draft of the page up here:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/BootCamp/resources/awardees/phase-1/bootcamp/

Just a note on styling- Accessibility standards like having an h1 tag if you are going to have subheaders farther down the page, so I added a page title. But our current style guide makes the first paragraph under the title bold and a little larger than the rest of the body text. So that's why the first paragraph is emphasized. Just wanted to give an explanation!

**Comment by kmonterr** [comment]
Thanks, @seakhtar !

Can you make one more change? It is bolded here and located in the Budget section.  Then we should be good to push live - 
Phase I applicants may budget up to $20,000 of their Phase I award funds to cover costs for the NSF’s “Beat-the-Odds Boot Camp.” Refer **to the budget preparation instructions in the solicitation or** the FastLane Guide for more information.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

The line has been changed and the page has been published to the master branch!

**Comment by kmonterr** [comment]
thanks, @seakhtar !
