### ISSUE TITLE
Adding a New Program Director & API Updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1204]
Hi Sarah - 
Can you please add Steve Konsek to the contacts page? He will be covering Advanced Instrumentation and Materials. (Can you update the API??) Here's his email address too: skonsek@nsf.gov

Here's his bio and photo:
Steven Konsek joined the National Science Foundation’s SBIR/STTR program in 2012 and has served as both a Program Director for the SBIR/STTR and the Innovation Corps (I-Corps™) program. Prior to joining NSF, Steven was the Chief Technology Officer at Illumitex, a venture-backed company developing light emitting diode chips, packages and fixtures for general illumination. He previously served as Chief of Technical Staff at Glo, recognized as one of Europe’s top LED startups. Prior to Glo, Steven was the Director of Device R&D at Nantero, a memory startup. Throughout his career, Steven has developed innovative, game-changing technologies across a range of semiconductor applications. He holds numerous patents and publications in LEDs, memory, process integration and nanoscale devices. Steven has a Ph.D. in Physics from the University of Washington and a B.S. in Mathematics from Purdue University.  
![steve](https://user-images.githubusercontent.com/26437393/41980062-9301fd34-79f3-11e8-9a17-142409f036d0.jpg)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've added Steve into a test branch here: https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/konsek/contact/

I think that should display him as the PD everywhere on our website. I can't directly edit the API as it is created by NSF's database- this is sort of our continuing issue of how to manage pulling information from NSF when it doesn't quite match up with what we're putting on the site. Our developer and I are in the process of developing a workaround.

Do you know if NSF updates their database every time they get a new PD? So that all awards that were in the MI tech topic are now listed as having Konsek as a PD? I've been looking it over and I'm not sure the NSF database records the tech topic of an award. 

But let me know if the link above looks okay and if it's all set to push.

**Comment by kmonterr** [comment]
Hi @seakhtar !

It looks good! Feel free to push it live!

Steve isn't fully integrated into the NSF database yet, but yes, when a new PD takes on a portfolio, the database reflects it. It moves the awards to the right PDs. the problem is - it doesn't account for tech topic, so the only way to show the topic is by PD, which is not always correct. They're looking at fixing the API in the future.

Let me know if you ever want to check in on this!

**Comment by seakhtar** [comment]
Great- thanks for clarifying things! I'll push forward on the workaround for now, but it's good to know that they might just update the system anyway as that would probably be a more robust solution to the problem.

But everything has been pushed to prod, and it looks like it's displaying okay!
