### ISSUE TITLE
Fix Links to Webinars on For Applicants Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1222]
There's some sort of bug on the For Applicants Page **-https://seedfund.nsf.gov/resources/applicants/**

I changed the links to the recorded webinars months ago, but now they are going to webinars recorded in 2016. I just tried to update the links again, but it doesn't work for me. it's under the Q&A videos header
 Can you please help?

Webinar: What is America's Seed Fund at NSF? - should link to:
https://www.youtube.com/watch?v=jjhD5sT4a64

How to apply should link to:
https://www.youtube.com/watch?v=tKSCgTXkSXc

**Comment by seakhtar** [comment]
Hi @kmonterr ,

The links should be working properly now- you can check it out on the live site!

Looks like there are two versions of code for the QA links in the For Applicants page. The first version is for when the site is active, and the second is for when the site is inactive. So when we switched the site to inactive mode, it started to use the code that hadn't been updated with the new links. 

I think is was done that way so that we could have different sets of videos depending on what state the site was in. But if we just want to use the same videos, that means an extra step of pasting the links into both versions of the code. 

Let me know if I need to explain that better!

**Comment by kmonterr** [comment]
makes sense! Thanks, @seakhtar !

**Comment by kmonterr** [comment]
https://www.youtube.com/watch?v=tCdvg73HtyQ&feature=youtu.be
