### ISSUE TITLE
Updates to the FastLane pages and PDF guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1247]
We marked up the FastLane guide PDF that is downloadable from the website to indicate the areas that need new instructions or screenshots.  The Word file attached includes the updated screenshots (mostly – see below).  I hope my notes/markups are clear enough to follow – but we can chat this week if you have questions.

The only outstanding issue is the final submission steps.  We are waiting for
[FastLane updated print screens (Aug 2018).docx](https://github.com/18F/nsf-sbir/files/2325320/FastLane.updated.print.screens.Aug.2018.docx)
[Uploading Phase_I_Proposal_Preparation_Booklet (AM markups Aug 2018).pdf…]()

 the final few screenshots for those new steps. Hopefully, we get them soon! Let me know when you have mocked up the site and PDF with these updates for review. 

Thank you!

**Comment by kmonterr** [comment]
Hi @seakhtar - 

Do you mind looking at this issue next? There are a lot of changes in the FastLane guide....

Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr -
I'm looking into this one now- I'll try to get it back to you ASAP.

**Comment by seakhtar** [comment]
Hi @kmonterr 
When you get a chance, can you go over the PDF and see if I've added the new screenshots in the correct place?
I'm getting them uploaded to the website pages, but I figured it would be good if you got a look now:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/FastlaneUpdates/assets/files/applicants/Phase_I_Proposal_Preparation_Booklet.pdf

Thanks!

**Comment by kmonterr** [comment]
[Phase_I_Proposal_Preparation_Booklet (AM markups Aug 2018) 09_11.docx](https://github.com/18F/nsf-sbir/files/2375771/Phase_I_Proposal_Preparation_Booklet.AM.markups.Aug.2018.09_11.docx)

Hi @seakhtar ! Thanks so much for pulling them together. Here are the remaining screenshots and instructions for the FastLane guide ( pages 30-35 of the attached).  Once you make the updates, let me know and a few of us will review very closely!

**Comment by seakhtar** [comment]
Hi @kmonterr 
I focused this time on getting the webpages updated- they are easier to change than the PDF, so that way I could double check with you before messing with it! I was just finishing up looking for any typos or image display error, but here is the link so that you can start looking things over:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/FastlaneUpdates/fastlane/
I was just doing a final check last night. In the second Word Doc I got, there were some places where I had a few questions

- on pgs 4 and 30 there seem to be notes that are for internal use, and I wasn't sure if there would be more updates for those pages? 

-it looked like any red text was just signifying something had been updated, but there were some places where the red might have looked like it was emphasis? If so, let me know which pages and I'll update it

-there were some things on the word doc that weren't marked as a tracked change, but it looked different from what was currently on the site. I've updated things to match the word document.

-I used the screenshots from the first word document you sent me, where applicable. I mention this because some of them didn't quite match up and it looked like your versions were the newer ones.

**Comment by kmonterr** [comment]
Hi @seakhtar - I sent this yesterday via email, but wanted to make sure it was all in one place!

Notes below and attached:

•	External links should always open in a new window, so they don’t have to navigate back to the FL guide.
•	Links to DUNS right near the top is broken.
•	There are a few gaps between sections that could be made smaller, I am very anti-blank space on the screen – just adds to the scrolling.
•	We need to apply consistent messaging about how long SAM registration could take – Please change all language to SAM registration can take up to one month or more 
•	The first page is largely about registrations and screenshots
[FastLane guide edits for website (09202018).docx](https://github.com/18F/nsf-sbir/files/2406476/FastLane.guide.edits.for.website.09202018.docx)
 are from Research.gov and then near the bottom a sectional called “Create Proposal” moves the user over to FastLane.  I recommend that this section move to the top of a new page called “Create Proposal in FastLane” that leads more cleanly into the “Form Preparation” screens.

See attached print screens and notes for additional updates and corrections.

**Comment by seakhtar** [comment]
Thanks @kmonterr -- that document makes it easier to see what we're going for! 

For the images- I've taken them from the second word doc you sent. I noticed that a lot of them were small, and I had to try to export them from word which might have affected the resolution. If they have the original images just as jpegs and could send them to me in a zip file, they might be larger or clearer. I will also try to remove that gray box on page six, but since it's covering part of the title, it might not look right. It might be better if we can retake the picture, if possible. 

I'll let you know once it's ready!

**Comment by seakhtar** [comment]
Hi @kmonterr 
Do you mind doing another quick run-through of the Fastlane Guide? I'm not sure I got your request about the "create proposal" section the way you wanted, so I wanted to give you a chance to look that over- https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/FastlaneUpdates/fastlane/form-prep/

I've also attempted to get the other changes you wrote out implemented, but if there are any further adjustments needed let me know!

**Comment by kmonterr** [comment]
[FastLane edits 10.10.2018.docx](https://github.com/18F/nsf-sbir/files/2465133/FastLane.edits.10.10.2018.docx)
Hi @seakhtar - Here are the last 4 changes! Let me know if you have any questions.
Kelly

**Comment by seakhtar** [comment]
Thanks @kmonterr - I'll let you know when it's ready to review!

**Comment by kmonterr** [comment]
Thanks, @seakhtar -

We are looking at the end of it again. I'll let you know if there are more changes.

We also need to fix the formatting instructions - Here's the corrected version- 

•	Arial, Courier New, or Palatino Linotype at a font size of 10 points or larger
•	Times New Roman or Computer Modern family of fonts at a size of 11 points or larger
•	_A font size of less than 10 points may be used for mathematical formulas or equations, figures, table or diagram captions and when using a Symbol font to insert Greek letters or special characters, but the text must still be readable._
•	No more than six lines of text within a vertical space of one inch.
•	Margins, in all directions, must be at least an inch.
•	Proposers are strongly encouraged to use only a standard, single-column format for the text.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just finishing up adding those adjustments and I had a couple of quick questions. 
For # 2 "Separate the print screens" - can you talk about that one a little more? I wasn't quite sure which images it was referring to

And for # 4 where it mentions adding more space between screenshots, I just wanted to make sure I had the right ones- were you referring to the cover sheet ones:

![screenshot-federalist-proxy app cloud gov-2018 10 12-09-44-56](https://user-images.githubusercontent.com/28659251/46873212-01c9e600-ce04-11e8-891a-b116ed60dfad.png)
 
Once I get that cleared up, we should be all set for any further changes. Thanks!

**Comment by kmonterr** [comment]
Hi @seakhtar -

Just add a couple more spaces between the screenshots on this page:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/FastlaneUpdates/fastlane/
for instance:
![image](https://user-images.githubusercontent.com/26437393/46874579-78b4ae00-ce07-11e8-9525-3f3669547b91.png)

**Comment by kmonterr** [comment]
Hi @seakhtar - Once you do that, please push it live! I think we'll have a couple other things coming, but I'd rather get this up now :)

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sorry thought I had replied to this! The spaces are in place, just let me know if you'd like them to be bigger or smaller. I'll go ahead and publish in the meantime!

**Comment by kmonterr** [comment]
YAY! Thank you, @seakhtar! two more things! my colleague who is the proposal queen just responded when you did! her ears must have been ringing.

1. There is an upside down print screen at the very bottom of this page (under Other Supplementary Docs):https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/FastlaneUpdates/fastlane/form-prep-3/

2. Can you please update the downloadable PDF to mirror the updated live site as well?  Thank you thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr -
I've updated the screenshot in dev, but it looked like you were doing some work there so I haven't pushed it to the master branch just yet. Let me know if you'd like me to go ahead.

Regarding the PDF- with the new updates it would take too long to edit it directly, so I figured it would be better to create a new word doc instead. I managed to get about halfway through before I turned my attention back to the site, but I'll focus on getting it finished up now that we have all of the updates in place!

The only caveat is that once I make it a PDF, I will need to redo the 508 compliance on it, which can take some time because of all the images. I'll try to get it finished up asap, but I wanted to give you a heads up as to why there might be a delay. If you need it up as quickly as possible, we could maybe publish the PDF first and then replace it with the 508 version once it's done? Just let me know.

**Comment by kmonterr** [comment]
Hi @seakhtar - awesome! I'm done with my changes. Feel free to push it live! Do you mind looking at my fixes for the portfolio page?? I have to present it tomorrow at 10 am. 
I like the idea of publishing the PDF and then replacing it with the 508 compliant version. Let's do that! THANK YOU THANK YOU!!!!!!!!

**Comment by seakhtar** [comment]
Hi @kmonterr - 
It's been pushed to the master branch! Had just a couple of notes on the portfolio issues, but I put it in the New Topics thread.

**Comment by kmonterr** [comment]
Thanks, @seakhtar !

**Comment by seakhtar** [comment]
Hi @kmonterr 

So I have an updated version of the PDF guide that I've tried to match up with what's on the site. I'd like to work a little more on the format (make the headings clearer and the spacing/image sizing more consistent), but I figured it might be best just to even get a basic form of the updated version in place.

I've put it on dev, but here it is as well-- I think I got all the changes, but if you notice anything off, let me know. Some of the screenshots might be too small? It's always a struggle between trying to keep them readable and minimizing the white space that crops up when they get kicked to a new page-

[Phase_I_Proposal_Preparation_Booklet.pdf](https://github.com/18F/nsf-sbir/files/2492712/Phase_I_Proposal_Preparation_Booklet.pdf)

If everything looks okay, I'll push to production and start working on the 508 compliance.

**Comment by kmonterr** [comment]
hi @seakhtar - got it! Here's the last piece of the FastLane guide (on the site and the PDF). Please put this paragraph at the end of section 1 (under the links to the registration sites). THANK YOU!

For SBIR applicants with subawardees and all STTR applicants, the subawardee should be registered in SAM. If the sub awardee organization is NOT registered in SAM, the principal investigator (PI) or a representative at the subawardee organization can call the research.gov  or FastLane Help Desk. NSF will manually register them as an institution in the NSF system.

**Comment by kmonterr** [comment]
YES! Looks great. Please publish away!!! :)

**Comment by seakhtar** [comment]
Okay, it's been merged with the master branch and should show up soon!

**Comment by kmonterr** [comment]
Woohoo! Thanks, SARAH!!!
