### ISSUE TITLE
EdTech Porfolio Companies Update

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1324]
please add these companies to the edtech topic of the portfolio page!

Edify: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660072
Killer Snails: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660065
Cue Think; https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660216&HistoricalAwards=false
AlChemie: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1659983
Couragion: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660021&HistoricalAwards=false
Speak Agent: https://nsf.gov/awardsearch/showAward?AWD_ID=1632488&HistoricalAwards=false
Zyrobotics: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1555852
ThoughtStem: https://nsf.gov/awardsearch/showAward?AWD_ID=1632539&HistoricalAwards=false
Looking Glass Ventures: https://nsf.gov/awardsearch/showAward?AWD_ID=1758301&HistoricalAwards=false

**Comment by seakhtar** [comment]
Hi @kmonterr 

I've added these to a test branch. They might not all show up right away due to the number of companies-- it didn't sound like you wanted me to remove the previous set, so I've left them in as well, but let me know if you'd like to see the full list!
Here is the test branch:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/edTech/portfolio/

**Comment by kmonterr** [comment]
Hi Sarah!

You can remove the old companies! THanks for the quick turnaround!

Kelly

**Comment by seakhtar** [comment]
Sure! I've removed the old companies and pushed everything to production.
