### ISSUE TITLE
Broken link - to definitions page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1325]
The IIB website (https://seedfund.nsf.gov/resources/awardees/phase-2/supplement/) gives a link for the Definition of a third-party investor: https://www.nsf.gov/eng/iip/sbir/definitions.jsp#thirdparty.  This link is not active. When I paste it into the address bar of the browser, I go to the generic seedfund.nsf.gov website, with no obvious definition available.

It should direct to https://seedfund.nsf.gov/fastlane/definitions/ to the third party definition.

**Comment by seakhtar** [comment]
Hi @kmonterr 

This one seemed like a quick fix so I just made it on dev. I made the link clickable and added the ID tag so it jumps to the correct section. Let me know if you'd like me to make any other changes- otherwise I'll push to production:
https://github.com/18F/nsf-sbir/blob/dev/pages/resources/awardees/phase-2/supplement.md

**Comment by kmonterr** [comment]
please push it live! Thank you!!

**Comment by seakhtar** [comment]
Okay, it's been pushed!
