### ISSUE TITLE
Update For Applicants Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1409]
Hi Sarah -

Can you please update the For Applicants Page?

Q&A webinars
Thinking of applying for Phase I funding? Ask all your application-related questions during our Q&A webinars. Can’t make it to a webinar? Watch a recorded webinar about the Project Pitch Pilot [the link - https://youtu.be/xZO8o1mDiO0}

. (We offer a PDF version of program basics, too.)

Can you please update the PDF on the site too? I think it is also linked on the ABout page?

[overview one-pager 2019_project pitch.pdf](https://github.com/18F/nsf-sbir/files/2972433/overview.one-pager.2019_project.pitch.pdf)

THANK YOU!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So, I thought I missed this issue, but it does look like it's already been completed? The only difference is that "recorded webinar" is linked rather than "Project pitch pilot". The PDF is already updated, but I didn't see a link on the About page. There was one on the Press page, but it's been updated there already as well. I think I remember talking about this all with you, so maybe we handled it in another email? 

Just wanted to make sure everything is okay, since this issue was open and had no reply from me on it!

**Comment by kmonterr** [comment]
I think it's all good???
