### ISSUE TITLE
Failed builds - Ruby Problem?

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1422]
Hi Sarah!

I'm updating the PD bios and the portfolio page. Sadly, they didn't build properly! Federalist says it's something about Ruby?

Can you please take a look when you have a chance and push it through?

Thanks!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

It looks like the issue was an extra apostrophe in the program-directors data file. It's a little confusing because when you look at the error logs the error shows up at towards the end, but not at the _complete_ end. It will always add a bit about ruby there but the actual error is usually a couple of lines up! Wasn't sure if you were using the federalist site to check the errors, but it took me a while to figure that out. 

Anyway, dev is now building correctly. Let me know if you'd like me to push it to master or leave it be for you to keep working on!

**Comment by kmonterr** [comment]
Hi @seakhtar - 

Thank you for checking it out! The portfolio updates are working on Dev, but the Bio updates haven't been pushed. Weird, right? Do you mind checking it out too? Whenever it works please push to Master!

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Finally figured it out- I forgot that the program-directors.yml is one of those data files that is dynamically created. Bios are actually updated through the tech-topics.yml file, so I transferred all the changes there. I've pushed it to the master branch-- I think it got all the things you adjusted, but let me know if anything looks off.

**Comment by kmonterr** [comment]
Looks good! Thanks, Sarah!
