### ISSUE TITLE
Edit the bios

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1539]
I found typos in the staff bios and PD bios on the site. here's the corrected version with tracked changes!
[Staff Bios_9.3.2019_for web.docx](https://github.com/18F/nsf-sbir/files/3571378/Staff.Bios_9.3.2019_for.web.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Real quick question-- it looks like some of these edits are already in place on the [biography page](https://seedfund.nsf.gov/contact/bios/). I wanted to check if there was a separate biography page that you saw besides the one above (or if these were just additional updates)? It also seems like some of the wording on the current biographies are a little different than the wording on the word document (not just the tracked edits). I think we might have used a different document last time. Would you like me to go ahead and copy over these new ones so that they match up completely? 

Hope I explained myself okay-- let me know if you'd like me to write out an example.

Thanks!

**Comment by kmonterr** [comment]
Hi @seakhtar -

Hmmm. Maybe replace the ones that are online with these? I will socialize and see what people want!

Thank you so much!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've put the updated bios on a new branch and I just had a couple quick questions.

-Muralidharan Nair's  bio has his name listed as "Muralidharan (Murali) S. Nair". Since the bio gets his name from the master tech-topic file, that means if I change it, it will show up like that everywhere his name is listed (the portfolio page, contact page, topic page). Is that okay? 

-These are really nitpicky, but it looks like all the bios say the pds are "*a* SBIR/STTR Program Director". Anna's bio says she "joined the National Science Foundation as SBIR/STTR Program Director", so I figured there's supposed to be an *a* there. And Rick's has him listed as "the SBIR/STTR Program Director", so thought that might need to be an *a* as well. Just let me know if I should change them back.

I'll hold off on publishing on your say-so-- wasn't sure if you wanted to wait until you hear back from the others, but with the two questions above taken care of, it should be ready to go!

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/bioUpdates0919/contact/bios/

**Comment by kmonterr** [comment]
hi @seakhtar -

Thanks for checking!

-Can you please just change Muralidharan to "Murali"? Everyone calls him that! It'll be easier and would be great to have it across the site!

-Please add an "a" before SBIR/STTR for each (Like you proposed!)

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Just wanted to fill you in that these last changes have been made and the bios are now up- let me know if you'd like me to make any other updates!

**Comment by kmonterr** [comment]
Thanks, Sarah!
