### ISSUE TITLE
Alphabetize the bios page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1610]
can you please alphabetize the Bios page?
https://seedfund.nsf.gov/contact/bios/

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I think this is actually something we've wanted to do in the past. The issue was that this page is created dynamically-- it lists the names in the same order as they are presented on the portfolio page, since they use the same data file for their information.

I'm going to try playing with the scripting to get it to display differently, but I wanted to give you a heads up that it might take a bit longer than if I'd just been able to manually rearrange them!

**Comment by kmonterr** [comment]
Thanks, Sarah! I remember that this is a problem...let me know if you all can figure it out!

**Comment by seakhtar** [comment]
Managed to figure it out- the bios are now alphabetical!

https://seedfund.nsf.gov/contact/bios/
