### ISSUE TITLE
Trouble with Webinars

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1626]
Hi Sarah - I made the mistake of deleting the code and trying to fix it. Do you mind looking at the dev code to see why Virtual Office Hours isn't showing up?? It's driving me nuts!
Thank you!
https://github.com/18F/nsf-sbir/blob/dev/_data/events_upcoming.yml

**Comment by seakhtar** [comment]
Sure-- I'll take a look! I always have trouble with that events page, haha.

**Comment by seakhtar** [comment]
Hi @kmonterr -
Actually, it does look like there's a second VOH event listed- unless you had a third you wanted to add.
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dev/events/

Maybe Dev was just taking a long time to build?

**Comment by kmonterr** [comment]
haha I hate it!! No, look at this. It's the title that is missing. Look what's on the live site - https://seedfund.nsf.gov/events/ The big, pretty Virtual Office Hours title. I'm not sure why it doesn't show up! I even copied the original code from the staging site to test it and it didn't work. weird, right?

**Comment by seakhtar** [comment]
Got it-- I see what you're saying now! I'll check it out.

**Comment by seakhtar** [comment]
Okay, looks like we had a space between event and Name, instead of eventName. It's showing up now!
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dev/events/

I've also gone ahead and updated the wiki, since it had it wrong in it's instructions. 
https://github.com/18F/nsf-sbir/wiki/How-to-Update-Events-page

Let me know if you'd like me to go ahead an publish!

**Comment by kmonterr** [comment]
OMG. THANK YOU!!!

Yes! Please publish!
Thank you so much!

**Comment by seakhtar** [comment]
Just confirming that this is now on prod!
