### ISSUE TITLE
Remove Prior Deadline

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1685]
Hi Sarah -

This page:
https://seedfund.nsf.gov/project-pitch/

still references the 2019 deadlines 

Can you please link it to the new windows or use what we used to use with the past submission dates to ensure that we capture all of the deadlines??? 

Please do a site-wide search to make sure that it isn't anywhere else too.

Thanks!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've updated the Project Pitch page on dev, but can you check my wording to ensure it looks the way you'd like?:
**(The submission windows for 2020 are December 18-March 5, March 6-June 4, June 5-September 3, and September 4-December 3)**

I'm sorry for missing this- I'd forgotten we had it there too.

The site does have the capability to auto-update the next deadline, but I think we actually removed the only instances it was used (on the About page, and at the top of the Apply page). Since then we've updated the site manually:

The problem we run into is that using a variable to update site-wide basically acts as a find and replace- there is no logic behind the formatting. So on the Apply page, we list the submission dates in this format: 12/18/2019 - 3/5/2020 and this format: December 18, 2019 - March 5, 2020. The Project Pitch page uses them in a sentence with a format of December 18-March 5, and the 2020 updated separately. We could try using the same format for all three locations, but we'd also need to make multiple variables for each submission window. If you'd like me to look into this, let me know and I will get a test branch set up.

I  can also create a wiki page detailing the locations where the submission windows and deadlines are referenced. That way, when it came time to update the site we'd have a reference to make sure we weren't forgetting anything. We would just have to make sure to keep it updated as we change the wording on the site. 

Sorry for missing this- I will be combing through the site to make sure there are no other instances. If the wording above looks good, let me know and I'll push it to production.

**Comment by kmonterr** [comment]
Hi @seakhtar -

Thank you!

I found another instance - 
https://seedfund.nsf.gov/fastlane/

Please try making the test branch with multiple variables. Please write out the full month name and date if possible. The formatting shouldn't hold this up - e.g. March 5, 2020 instead of 3/5/2020.

Please let me know if you have other questions! 
Kelly

**Comment by seakhtar** [comment]
Sure- I'll get started now and will send along a test branch once I have it completed!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've created a set of variables to use throughout the site:
next_deadline: March 5
solicitation_window_1: December 18, 2019 - March 5, 2020
solicitation_window_2: March 6, 2020 - June 4, 2020
solicitation_window_3: June 5, 2020 - September 3, 2020
solicitation_window_4: September 4, 2020 - December 3, 2020

Here are the affected pages-- let me know if you'd like me to adjust the wording on any of these:

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dateVariable/apply/ (at the bottom and in Step 4)

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dateVariable/project-pitch/

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dateVariable/fastlane/

If they look okay let me know and I'll go ahead and publish them. Or, if you need me to make any adjustments, let me know-

**Comment by kmonterr** [comment]
Thank you, Sarah!

This looks good!

Can you change the text on this one?
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dateVariable/fastlane/

From:
If you were invited and unable to submit your proposal before the submission window closed on December 12, please reach out to your program director about next steps. The submission window will close on March 5. We encourage you to follow guidance from your program director for when and how to submit your proposal. FastLane will not accept proposals after 5:00 PM submitter’s time on March 5.

To:
FastLane will not accept proposals after 5:00 PM submitter’s time on (next Variable date here). A new submission window will open (subsequent variable). We encourage you to follow guidance from your program director about when and how to submit your proposal.

Thank you! When it's done, please push it live!
Kelly

**Comment by kmonterr** [comment]
Thanks, @seakhtar !
I think it this looks good! Just to confirm on Fastlane the March 6 language is a variable, right? I don't want to have to remember to change this every time!

*FastLane will not accept proposals after 5:00 PM submitter’s time on March 5. A new submission window will open March 6. We encourage you to follow guidance from your program director about when and how to submit your proposal.*

Otherwise, it's all good. Please push it live.
Kelly

**Comment by seakhtar** [comment]
Yes- I made one more variable since it seemed like using a window didn't quite fit the phrasing. Or I can just use the window if you prefer to keep things simple? 

Either way, they're all in the same place, so we just have to remember to switch them out when necessary!
