### ISSUE TITLE
Linking to the topics doc on all topic webpages

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1774]
Hi Sarah -

Cecile had a good suggestion to link to the topics pdf from each topic webpage on seedfund. She said it's pretty hard to find (since it's only in two/three places).
For instance on Biomedical - https://seedfund.nsf.gov/topics/biomedical-technologies/ - would you suggest that we put it on the left as a link under Henry's info? That might be an easy place to see it on all of the pages.

I'm open to suggestions. I would just propose that we use the variable so we don't have to remember to update this link everywhere when we update the topic pdf every year.

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

So with the way the topics pages are created, adding a variable didn't quite work with the code. But (unless there are any reasons not to do so), in the future I can just name the file something generic rather than including the date (ie, tech-topics.pdf). That way, each time I upload a new one with that filename the links will all already be pointing at it, which comes out to about the same thing.

How does this look?
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/topics/advanced-manufacturing/
