### ISSUE TITLE
showcase bug - YouTube

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1963]
Hi Sarah -

There's a bug with our youtube video player. I cannot "watch the video in YouTube" when I click on the option on the video.

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

@mpadigala and I looked into this and it appears to be related a security setting we added to the embedded videos during the last security audit. One side effect of the script is that it doesn't allow new windows to be created from the embedded video links. 

We can go ahead and remove the broken "Youtube" button so that it doesn't show up in the controls. Then, if you'd still like users to have the option of going to the site, we could try creating a new one underneath the video? (The only alternative would be to remove the script instead, but that would flag the page in future security scans.)

Let me know if you like me to add a button in, or just remove the old one!

Thanks-
Sarah

**Comment by kmonterr** [comment]
Hi Sarah!

Can you please remove the broken button and mockup creating a button that would drive people to YouTube?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi Kelly,

Here is a draft of the branch-- let me know if you'd like me to make any adjustments!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/youtubeLinkFix/showcase/

**Comment by kmonterr** [comment]
Hi Sarah! This looks good! Can you please make sure the links go directly to each video on YouTube?

Also, is it possible to remove the little NSF logo and the title from the screenshot on the Showcase Page? I think I've asked before, but maybe it's possible now?!

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi Kelly--

The links underneath each video should be going to each video's youtube page. Are you seeing something different?

I've checked again, but unfortunately Youtube still seems pretty adamant about keeping the title and channel icon in place. There used to be a parameter you could use to turn it off, but they specifically removed it. I haven't been able to find any workarounds yet, but I'll keep an eye out!

**Comment by kmonterr** [comment]
Looks good! THanks, Sarah! Please publish.

If they allow the option in the future, let's do it!
