### ISSUE TITLE
Changing WebEx to Zoom

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2032]
Hi SArah!

Can you please change the reference to Zoom on this page? (where it says webex?)
https://seedfund.nsf.gov/resources/review/virtual-panelist/

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've gone in and [changed all mentions of WebEx to Zoom](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/resources/review/virtual-panelist/). There was a link to a document instructing people how to log in to WebEx-- since it was specifically about the application I went ahead and removed that as well. Let me know if I have that wrong and I'll stick it back in. Otherwise, I'll go ahead and publish!

**Comment by kmonterr** [comment]
Thank you!!

**Comment by seakhtar** [comment]
Great- this has been completed!
