### ISSUE TITLE
Links on the Portfolio Page for Education (EA topic) appear to be incorrect

### ISSUE THREAD

**Issue by bonnieburckel** [18F/nsf-sbir#940]
## Steps to reproduce the behavior
- [ ]
- [ ]
- [ ]

## This issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by bonnieburckel** [comment]
Hi! I just checked out all the links under the EA topic and none are associated with the EA topic.  Assume its just pointing to the wrong list.  Thanks for checking into it!

**Comment by kmonterr** [comment]
Thank you, @bonnieburckel ! We'll have our developer take a look.

**Comment by kmonterr** [comment]
Hi @bonnieburckel -

We were looking at the site. They appear to be correct for us? This is the list that we see - Mgenuity
Launchpad Central 
Modular Robotics
Zyante Inc
Voice Vibes
KinderLab
Killer Snails
Teachley
Second Ave Software
Simbulus
Workplace Tech
Edify
Triad Interactive
StarMobile
ecoAtm

Let us know if you're seeing something different! @seakhtar

**Comment by bonnieburckel** [comment]
Hello!  Thanks for the quick response!  Yes, I see something different.  Here's how I'm getting to where I'm getting:  
Start here:   https://seedfund.nsf.gov/portfolio/ 
Then: https://seedfund.nsf.gov/awardees/phase-1/ 
Then click on "Educational Technologies and Applications (EA) to expand list.
I see: 
2W iTech LLC
Abcombi Biosciences,, Inc.
Aerosol Devices, Inc.
Azimuth1, LLC
<<and onward ... down to the last one listed is ...>>
 Vault Nano Inc.
These companies don't appear to have an Education bent (as in they are solving other issues/cool projects not Educational topics) which made me think that the Education Phase I Awardees are not "loaded" or "linked" correctly.  (I might not be using the correct terminology there... :) )  

Ok, let me know what you think!  Thanks! - Bonnie

**Comment by kmonterr** [comment]
Thank you, Bonnie! We'll look at this page! 
@bonnieburckel @seakhtar

**Comment by seakhtar** [comment]
Okay, I've looked this over and there's a bit of a snag:
-The Phase-I awards page Bonnie is talking about dynamically takes the PD associated with a topic in the tech-topics.yml data file to look through the awards-phase-i.yml data file and pull out the awards associated with that PD.
-So Ben Schrag is listed as the EA PD in the tech-topics file, but all of the EA awards are associated with Larsen in the awards file. That's why only Schrag's awards are showing up.
-But we can't change the PD name in the tech-topics file to Larsen, because the Portfolio page also displays the PD listed in the tech-topics file. So it would display Larsen as the PD.

At the moment, I see two options to fix the issue:
-Add something to Ben Schrag's name when it is specific to EA awards, ie, list his name as Ben Schrag (EA) in the tech-topics file. Then replace all instances of Erik Larsen's name in the awards file with Ben Schrag (EA). 
or
-Add a field to the tech-topics.yml file called something like "Display Name" to separate the name associated with the topic from the name that displays on the portfolio page. So Erik Larsen would be associated with the topic in the back end but all of Ben Schrag's info would display. 

@kmonterr  do you have a preference? Option 2 would look cleaner, but option 1 squares the front end with the back end (ie, one PD per topic, as opposed to two names per topic). 

Hope I explained all that okay- let me know if not.

**Comment by kmonterr** [comment]
@seakhtar Thank you for investigating! I think we should go with option 2 for the meantime! Do you mind testing it to make sure it works? Thank you!

**Comment by bonnieburckel** [comment]
Well done, team!  :)  Standing by to test it out also...  -- B

**Comment by kmonterr** [comment]
fixed! I'm pushing it live to the site now. Thanks for finding it, @bonnieburckel

**Comment by bonnieburckel** [comment]
I saw! (That you fixed it!)  I was out there yesterday and noticed you had them squared away.  Perfect & thanks!  - Bonnie
